import type { PlanetAgent } from './types.js'

const DEFAULT_PLANET_AGENTS: PlanetAgent[] = [
  {
    planet: 'Sun',
    agentName: 'Identity Agent',
    coreDrive: 'Identity, purpose, ego, visibility, and future self-direction',
    strength: 'Self-recognition, creative confidence, and coherent purpose',
    shadow: 'Pride, self-censorship, approval seeking, or inflated self-importance',
    trigger: 'Questions of who the user is becoming and whether they can be seen',
    decisionBias: 'Chooses paths that preserve identity, agency, and meaningful visibility',
    growthPath: 'Structured self-expression with humility and purpose',
    baseWeight: 0.62,
  },
  {
    planet: 'Moon',
    agentName: 'Emotion Agent',
    coreDrive: 'Feelings, safety, inner needs, memory, and emotional belonging',
    strength: 'Emotional attunement, care, intuition, and self-protection',
    shadow: 'Withdrawal, reactivity, clinging to safety, or unspoken need',
    trigger: 'Fear, vulnerability, attachment, uncertainty, or a need for comfort',
    decisionBias: 'Chooses paths that restore emotional safety and felt security',
    growthPath: 'Name the need clearly, then choose a safe enough next step',
    baseWeight: 0.58,
  },
  {
    planet: 'Mercury',
    agentName: 'Thought Agent',
    coreDrive: 'Thinking, communication, interpretation, learning, and sense-making',
    strength: 'Clarity, language, pattern recognition, and adaptive communication',
    shadow: 'Over-analysis, confusion, rationalisation, or looping interpretation',
    trigger: 'Ambiguity, mixed signals, planning, explaining, or needing language',
    decisionBias: 'Chooses paths that make the situation legible and discussable',
    growthPath: 'Translate the experience into clean words without escaping into thought',
    baseWeight: 0.56,
  },
  {
    planet: 'Venus',
    agentName: 'Value Agent',
    coreDrive: 'Love, values, attraction, pleasure, harmony, and relational worth',
    strength: 'Taste, bonding, receptivity, value clarity, and relational grace',
    shadow: 'People-pleasing, avoidance of conflict, vanity, or unclear values',
    trigger: 'Desire for connection, beauty, approval, affection, or value alignment',
    decisionBias: 'Chooses paths that preserve harmony, pleasure, and mutual value',
    growthPath: 'Choose what is genuinely valued without abandoning honest expression',
    baseWeight: 0.52,
  },
  {
    planet: 'Mars',
    agentName: 'Action Agent',
    coreDrive: 'Drive, anger, courage, desire, assertion, and movement',
    strength: 'Initiative, bravery, directness, energy, and protective action',
    shadow: 'Impulsiveness, aggression, impatience, avoidance through frustration',
    trigger: 'Blocked desire, urgency, anger, competition, or the need to begin',
    decisionBias: 'Chooses paths that create movement and recover agency',
    growthPath: 'Channel heat into clear, bounded, non-destructive action',
    baseWeight: 0.6,
  },
  {
    planet: 'Jupiter',
    agentName: 'Growth Agent',
    coreDrive: 'Belief, optimism, expansion, opportunity, wisdom, and meaning',
    strength: 'Vision, faith, synthesis, generosity, and long-range possibility',
    shadow: 'Overreach, inflated certainty, avoidance of detail, or naive risk',
    trigger: 'Opportunity, growth, learning, business upside, or a larger horizon',
    decisionBias: 'Chooses paths that expand capacity, meaning, and opportunity',
    growthPath: 'Expand through tested bets, honest feedback, and grounded wisdom',
    baseWeight: 0.57,
  },
  {
    planet: 'Saturn',
    agentName: 'Boundary Agent',
    coreDrive: 'Fear, discipline, duty, structure, delay, limits, and accountability',
    strength: 'Patience, responsibility, risk assessment, boundaries, and endurance',
    shadow: 'Rigidity, pessimism, shame, paralysis, or over-control',
    trigger: 'Risk, judgment, uncertainty, responsibility, cost, or long-term stakes',
    decisionBias: 'Chooses paths that reduce exposure and create durable structure',
    growthPath: 'Turn fear into proportionate structure and repeatable commitments',
    baseWeight: 0.64,
  },
]

export function getDefaultPlanetAgents(): PlanetAgent[] {
  return DEFAULT_PLANET_AGENTS.map((agent) => ({ ...agent }))
}
