export { BaseAdapter } from './base.js'
export { OpenClawAdapter } from './openclaw/index.js'
export { DockerAdapter } from './docker/index.js'
export type { DockerAdapterOptions } from './docker/index.js'
export { MockAdapter } from './mock/index.js'
export type { MockScenario } from './mock/index.js'
export { BashAdapter } from './bash/index.js'
export type { BashAdapterOptions } from './bash/index.js'
export { HttpAdapter } from './http/index.js'
export type { HttpAdapterOptions } from './http/index.js'
export { adapterRegistry } from './registry.js'
